using System;

namespace Entrenamiento.Nucleo
{
    public enum NombresDeInterruptores
    {
        Desconocido,
        Fuel_valve_button,
        Particle_separator_purge,
        Engine_anti_icing,
        Dim_caution_lights,
        Hydraulic_system_switch,
        Defog_blower_switch,
        Generator_switch,
        Battery_switch,
        Pitot_heat_switch,
        Position_light_switch,
        Anticollision_light_switch,
        Instrument_light_rheostat,// Perilla
        Cabint_lt,
        Att_ind,
        Generator_reset,
        Generator_field,
        Engine_start,
        Engine_igntr,
        Gov_cont,
        Dir_gyro,
        Eng_temp_ind,
        Fuel_qty_press,
        Fuel_left,
        Fuel_right,
        Tot_ind,
        Lights_caution,
        Lights_cockpit,
        Lights_instr,
        Lights_ldg,
        Aux_recp,
        Ibf,
        Xmsn_temp_ind,
        Heater,
        Hydr_system,
        Ics_phones,
        Ics_speakers,
        Adf,
        Vhf_2,
        Xpndr,
        Enc_alt,
        Floats,
        Cargo_hook,
        Hand_mike,
        Turn_ind,
        Fuel_valve_switch,
    }
}